# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20170401_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='member.Member'),
        ),
    ]
