# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170328_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(upload_to='static/games/images/thumbnail'),
        ),
    ]
