# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gameproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameproduct',
            name='item_ptr',
        ),'''
        migrations.DeleteModel(
            name='GameProduct',
        ),'''
    ]
