# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchaserecord_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.Item'),
        ),
    ]
