# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20170402_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 10, 53, 23, 435109)),
        ),
    ]
