# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_purchaserecord_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
