# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20170410_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='number_of_rewards_applied',
            field=models.IntegerField(default=0),
        ),
    ]
