# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_purchaserecord_number_of_rewards_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='number_of_rewards_applied',
            field=models.IntegerField(),
        ),
    ]
