# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='accumulating_spending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='images/avatars'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reward',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
