# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170411_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='images/avatars/default.jpg', upload_to='images/avatars'),
        ),
    ]
