# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_paymentmethod_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='member.Member'),
        ),
    ]
