# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20170412_1402'),
        ('member', '0006_auto_20170412_1335'),
    ]

    operations = [
    ]
