# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_merge_20170412_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='accumulated_spending',
            field=models.IntegerField(default=28),
        ),
    ]
