# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0007_gameproduct'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameProduct')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
    ]
