# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='game_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Item'),
        ),
    ]
