# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20170401_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
