# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchaserecord_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserecord',
            old_name='item',
            new_name='game_product',
        ),
    ]
