# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20170401_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserecord',
            old_name='game_product',
            new_name='item',
        ),
    ]
