# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 14:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_published',
            field=models.DateField(default=datetime.date(2017, 4, 29)),
        ),
    ]
