# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_published',
            field=models.DateField(),
        ),
    ]
