# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('RA', 'Racing'), ('RP', 'RPG'), ('SI', 'Simulation'), ('SP', 'Sports'), ('ST', 'Strategy')], max_length=2)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='images/thumbnails')),
                ('cover', models.ImageField(upload_to='images/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('L', 'Linux'), ('M', 'macOS'), ('W', 'Windows')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.Game')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('game', 'platform')]),
        ),
    ]
