# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('RA', 'Racing'), ('RP', 'RPG'), ('SI', 'Simulation'), ('SP', 'Sports'), ('ST', 'Strategy')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('thumbnail', models.URLField()),
                ('cover', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('L', 'Linux'), ('M', 'macOS'), ('W', 'Windows')], max_length=1)),
                ('price', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.Game')),
            ],
        ),
    ]
