# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_published',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('RA', 'Racing'), ('RP', 'RPG'), ('SI', 'Simulation'), ('SP', 'Sports'), ('ST', 'Strategy'), ('GG', 'GalGame')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='platform',
            field=models.CharField(choices=[('L', 'Linux'), ('M', 'macOS'), ('W', 'Windows'), ('W&M', 'Windows & macOS'), ('W&L', 'Windows & Linux'), ('M&L', 'macOS & Linux'), ('W&M&L', 'Windows & macOS & Linux')], max_length=5),
        ),
    ]
