# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20170328_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.Game'),
        ),
    ]
