# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20170401_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
