# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20170401_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
